### ISSUE TITLE
search method doesn't work

### ISSUE THREAD

**Issue by peppelinux** [vdmitriyev/orcidpyclient#4]
I fixed code for using orcid api search in my forked repo:
https://github.com/peppelinux/pyorcid

PR here: https://github.com/vdmitriyev/pyorcid/pull/5

**Comment by vdmitriyev** [comment]
Thanks for your contribution. I will check your code and try to merge it as soon as possible into main repository. To be honest, I never used the "search"  functionality and thought about removing it completely from the code base in the future.
