### ISSUE TITLE
Searching without knowing the full name of the author

### ISSUE THREAD

**Issue by flouland** [vdmitriyev/orcidpyclient#7]
Is it possible to search for an author without knowing the full name?

ex: 
#Only the first initial of the first name is known J. Wilbanks

`author = pyorcid.search(f'family-name:Wilbanks+AND+given-names:J')`

**Comment by vdmitriyev** [comment]
I think that this should work for you:

```python
authors = pyorcid.search('family-name:wilbanks&start=0&rows=3')
```

P.S.  Here ```rows``` means how many records to show/fetch, and ```start``` means where to start. More information on syntax of a potential query you can find in the tutorial from [ORCID](https://info.orcid.org/documentation/api-tutorials/api-tutorial-searching-the-orcid-registry/)
