### ISSUE TITLE
Searching for affiliations of a given author 

### ISSUE THREAD

**Issue by flouland** [vdmitriyev/orcidpyclient#8]
Is it possible to get the affiliations of an author via the api?

**Comment by vdmitriyev** [comment]
@flouland sorry for my late reply. I am going to check it and notify you soon

**Comment by vdmitriyev** [comment]
According to the article [Expanding Affiliations in ORCID: An Update](https://stackoverflow.com/questions/1720421/how-do-i-concatenate-two-lists-in-python) an *affiliation* in the context of ORCID means **education and employment**. Thus, I extended the library so it can use both as an affiliation. You need to update the library and then you can list the affiliations as follows:
```python
    import pyorcid
    orcid = '<ORCID>'
    author = pyorcid.get(orcid)
    print(f'Affiliations : {author.affiliations}')
``` 

I hope, it will help you further @flouland
