### ISSUE TITLE
Support for v3.0 API

### ISSUE THREAD

**Issue by pabloab** [vdmitriyev/orcidpyclient#9]
Please consider update [to v3.0 API](https://github.com/ORCID/orcid-model/blob/master/src/main/resources/record_3.0/README.md), [these](https://github.com/ORCID/orcid-model/blob/master/src/main/resources/record_3.0/README.md#changes-from-version-21) are the changes since the [currently used](https://github.com/vdmitriyev/orcidpyclient/blob/master/orcidpyclient/constants.py#L1) v2.1.

```json
{
  "expanded-result": [
    {
      "orcid-id": "0000-0001-5680-3441",
      "given-names": "Mariano",
      "family-names": "Suárez-Álvarez",
      "credit-name": null,
      "other-name": [],
      "email": [],
      "institution-name": [
        "IMAS. CONICET",
        "Universidad de Buenos Aires"
      ]
    },
    {
      "orcid-id": "0000-0002-2861-5547",
      "given-names": "Mariano",
      "family-names": "Quirós-García",
      "credit-name": null,
      "other-name": [],
      "email": [],
      "institution-name": [
        "Instituto de Lengua, Literatura y Antropología del CSIC"
      ]
    }
  ],
  "num-found": 2
}
```

More info [here](https://postman.orcid.org/).

**Comment by vdmitriyev** [comment]
Thanks you for opening this issue. I will give it a look.

**Comment by vdmitriyev** [comment]
@pabloab could you please have a look, if the latest update makes what you expect? Be aware that no new functionality was added to the library. For now, the upgrade to the 3.0 API version and compatibility tests were added.
